### ISSUE TITLE
Docker image broken - no notification because of lack of curl

### ISSUE THREAD

**Issue by maskimfr** [MollySocket/mollysocket#16]
Hello

I deployed mollysocket latest image (sha256:f246b71090c51211aa64487084856bfdb409d3dea1a603d03b21069d248ff05e) and I couldn't get it work. It didn't send notifications to my ntfy or nextpush server 

While trying to debug, I installed curl package (apt install curl) and it instantly worked. I could reproduce the issue and the fix multiple times.

**Comment by p1gp1g** [comment]
Thanks ! Do you have any error log ? I'll try it myself if not

**Comment by maskimfr** [comment]
I'm sorry, I didn't kept the logs.
I can try to get them tomorrow.

But there was no useful error (at least for me), even with debug enabled.

This is my docker file to fix the problem:
`FROM ghcr.io/mollysocket/mollysocket:latest

RUN apt -qq update && apt full-upgrade -y && apt -qq install curl -y && \
    apt-get autoremove -y && \
    apt-get clean  && \
    rm -rf /tmp/* \
        /var/lib/apt/lists/* \
        /var/tmp/ \`

The image can be downloaded here:
[ghcr.io/maskimfr/docker-images/mollysocket:nightly
](ghcr.io/maskimfr/docker-images/mollysocket:nightly
)

**Comment by maskimfr** [comment]
Hello

Sorry for the delay.
Logs for the image without curl:
[logs-with-curl.txt](https://github.com/MollySocket/mollysocket/files/12797683/logs-with-curl.txt)

Logs for the image I created with curl:
[logs-without-curl.txt](https://github.com/MollySocket/mollysocket/files/12797684/logs-without-curl.txt)

**Comment by p1gp1g** [comment]
I think the issue comes from the missing openssl package, which is installed as a dependency with curl. Could you try it ? And thanks for the report :)

BTW : This repo will move to https://github.com/mollyim/mollysocket

**Comment by p1gp1g** [comment]
We should try with libssl-dev too

**Comment by maskimfr** [comment]
Hello
I just did the test. The needed packages are :
openssl libssl-dev ca-certificates

Migration of the repo means that unifiedpush will be included soon in Molly ? This [PR](https://github.com/mollyim/mollyim-android/pull/152) is going to be merged soon?

**Comment by p1gp1g** [comment]
Thank you, I've updated the Containerfile to fix it.

> Migration of the repo means that unifiedpush will be included soon in Molly ? This https://github.com/mollyim/mollyim-android/pull/152 is going to be merged soon?

Yes ! We are doing a new official build of [Molly with UnifiedPush](https://github.com/mollyim/mollyim-android-unifiedpush/) support :)

**Comment by maskimfr** [comment]
Tried the new image, everything works, thank you !
Closing the issue.

One question, will molly with unified push be available on fdroid / accrescent ?

**Comment by maskimfr** [comment]
Hello

This commit made the issue happening again:
https://github.com/MollySocket/mollysocket/commit/2d4ff22874526494c3dda12f39d367e0cb4cfd79

ca-certificates is needed. Without it, mollysocket can't connect to a ntfy using https (certificate issued with letsencrypt in my case)

**Comment by p1gp1g** [comment]
@genofire it looks like libssl3 isn't enough and ca-certificates is still needed
