### ISSUE TITLE
Howto compile

### ISSUE THREAD

**Issue by genofire** [MollySocket/mollysocket#2]
I try to create an container image and got this error during compiling:

```
cargo build --release --bin mollysocket:
#10 270.9 
#10 271.0 error[E0554]: `#![feature]` may not be used on the stable release channel
#10 271.0  --> src/main.rs:1:12
#10 271.0   |
#10 271.0 1 | #![feature(ip)]
```

**Comment by p1gp1g** [comment]
I was thinking of adding this information ! And then I've seen your issue :sweat_smile:  . It requires rust nightly. That's because of the IP feature of std::net, to have *is_global(ip)*.

**Comment by genofire** [comment]
works - thank you

https://github.com/genofire/mollysocket/actions/runs/3597416320/jobs/6059143526

https://github.com/genofire/mollysocket/pkgs/container/mollysocket
