### ISSUE TITLE
Add metrics endpoint

### ISSUE THREAD

**Issue by genofire** [MollySocket/mollysocket#3]
to would be nice to have metrics for monitoring/alerting that mollysocket works correct.

An nice library is https://docs.rs/rocket_prometheus/0.10.0-rc.3/rocket_prometheus/index.html.

therefore it would be nice to have an prometheus / openmetric endpoint with gauge and counter like:
```
# HELP state is websocket connected
# gauge mollysocket_websocket_connected
mollysocket_websocket_connected{uuid="A",endpoint="https://ntfy.sum7.eu"} 1
mollysocket_websocket_connected{uuid="B",endpoint="https://ntfy.sh"} 0
# HELP counter of how man reconnect happen
# counter mollysocket_websocket_reconnect
mollysocket_websocket_reconnect{uuid="A",endpoint="https://ntfy.sum7.eu"} 3
mollysocket_websocket_reconnect{uuid="B",endpoint="https://ntfy.sh"} 1
```

### Alternative
if you do not like to have metrics labels by there uuid (and endpoint), it woukd be nice to have also an counter for not_connected.

```
# HELP current count of connected websocket
# gauge mollysocket_websocket_connected
mollysocket_websocket_connected 1
# HELP current count of not connected websocket
# gauge mollysocket_websocket_not_connected
mollysocket_websocket_not_connected 1
# HELP counter of how man reconnect happen
# counter mollysocket_websocket_reconnect
mollysocket_websocket_reconnect 3
```

---

other metrics like who many pings are active (and counter for failed) or so would be also nice

also an `up` with labels like version (and the value is calced e.g. 1=if database is accessible and so on 0=there is an problem:
```
mollysocket_up{version="0.1.0"} 1
```

**Comment by p1gp1g** [comment]
https://github.com/MollySocket/mollysocket/commit/bc9310a2801ecee91b9f9deddfd9f8208947c434

**Comment by genofire** [comment]
I create a small Grafana Dashboard for the new Endpoint (v0.2.1):
https://github.com/MollySocket/helm/blob/main/charts/mollysocket/grafana_dashboards/mollysocket-default.json

![Grafana Dashboard from HelmChart](https://github.com/MollySocket/helm/raw/main/charts/mollysocket/docs/grafana-mollysocket-default.png)

which is part of the Helm Chart -> maybe you want to documentate it here somewhere
