### ISSUE TITLE
Error while building a tagged container

### ISSUE THREAD

**Issue by p1gp1g** [MollySocket/mollysocket#9]
See https://github.com/MollySocket/mollysocket/actions/runs/4036411864/jobs/6938987218

>    /usr/bin/docker buildx version
  github.com/docker/buildx 0.10.0+azure-1 876462897612d36679153c3414f7689626251501
/usr/bin/docker buildx build --file Containerfile --iidfile /tmp/docker-build-push-gP2EYM/iidfile --provenance mode=max,builder-id=https://github.com/MollySocket/mollysocket/actions/runs/4036411864 --secret id=GIT_AUTH_TOKEN,src=/tmp/docker-build-push-gP2EYM/tmp-9922-bUmcCulWRXmm --metadata-file /tmp/docker-build-push-gP2EYM/metadata-file --push https://github.com/MollySocket/mollysocket.git#d2bbbe5c75613fd03615685c0ba2e3852c2c9a02
ERROR: tag is needed when pushing to registry
Error: buildx failed with: ERROR: tag is needed when pushing to registry

Ping @genofire, since you did the workflow :)

**Comment by genofire** [comment]
github-actions are new for me.
(i prefer gitlab)

so review and merge it ;)

**Comment by genofire** [comment]
Tag / Github release v0.2.1 does not point to a valid commit

**Comment by p1gp1g** [comment]
TIL `git push --tags` does not push commits too

**Comment by p1gp1g** [comment]
It works :)

**Comment by genofire** [comment]
FYI: `git push --tags origin main` works ;)
